#!/usr/bin/env bash
# loops 1-10 and displays 'bad luck','good luck', and 'Best School' in the 4th loop, 8th loop, and other iterations.i
x=0
while [ x -lt 10 ]
do
	if [ x -eq 4 ]
	then 
		echo bad luck
	elif [ x -eq 8 ]
	then
		echo good luck
	else
		echo Best School
	fi
	x=$(( x + 1))
done
